# Generated by Django 5.2.18 on 2026-10-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_history_and_tenant_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.asset')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.brand')),
                ('reference', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='studio.generationreference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
